title: CODEX 2026
description: GuideBook for CODEX 2026
theme: just-the-docs
color_scheme: dark

url: https://github.com/FaizaAlfa/CodEx_GuideBook

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

plugins:
  - jekyll-default-layout
